#!/bin/sh
if test ${WORDPRESS_VERSION}X = latestX; then
  wp core download --path=/var/www/html
else
  wp core download --path=/var/www/html --version=${WORDPRESS_VERSION} --force
fi
exec docker-php-entrypoint "${@}"
